apiVersion: v1
kind: Service
metadata:
  name: ptero-wings-controller
  namespace: ptero-system
spec:
  selector:
    app.kubernetes.io/name: ptero-wings-controller
  ports:
    - name: http
      port: 8082
      targetPort: 8082
