---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ptero-wings-gateway
  namespace: ptero-system
  labels:
    app.kubernetes.io/name: ptero-wings-gateway
    app.kubernetes.io/part-of: ptero-wings-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ptero-wings-gateway
  labels:
    app.kubernetes.io/name: ptero-wings-gateway
    app.kubernetes.io/part-of: ptero-wings-operator
rules:
  - apiGroups: ["gameserver.pterodactyl.io"]
    resources: ["gameservers", "gameserverclasses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["gameserver.pterodactyl.io"]
    resources: ["gameservers/status"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/exec", "persistentvolumeclaims", "services", "nodes"]
    verbs: ["get", "list", "watch", "create"]
  - apiGroups: ["apps"]
    resources: ["statefulsets", "deployments"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ptero-wings-gateway
  labels:
    app.kubernetes.io/name: ptero-wings-gateway
    app.kubernetes.io/part-of: ptero-wings-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ptero-wings-gateway
subjects:
  - kind: ServiceAccount
    name: ptero-wings-gateway
    namespace: ptero-system
