FROM golang:1.21 AS builder
ARG TARGETOS
ARG TARGETARCH

WORKDIR /workspace
COPY go.mod go.sum ./
RUN go mod download

COPY gateway/cmd/main.go ./
COPY gateway/internal/ gateway/internal/
COPY ptero-wings-controller/ ptero-wings-controller/
COPY api/ api/

RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -a -o gateway gateway/cmd/main.go

FROM gcr.io/distroless/static:nonroot
WORKDIR /
COPY --from=builder /workspace/gateway .
USER 65532:65532
EXPOSE 8090
ENTRYPOINT ["/gateway"]
