FROM golang:1.22 AS builder
ARG TARGETOS
ARG TARGETARCH

WORKDIR /workspace
COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod \ 
    go mod download

COPY ./ptero-wings-controller ./ptero-wings-controller 
COPY ./api ./api
COPY ./cmd ./cmd
COPY ./internal ./internal
COPY ./controllers ./controllers


RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -a -o controller-service ./ptero-wings-controller

FROM gcr.io/distroless/static:nonroot
WORKDIR /
COPY --from=builder /workspace/controller-service .
USER 65532:65532
ENTRYPOINT ["/controller-service"]
