FROM golang:1.21 AS builder
ARG TARGETOS
ARG TARGETARCH

WORKDIR /workspace
COPY go.mod go.sum ./
RUN go mod download

COPY ptero-wings-controller/ ./

RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -a -o controller-service ./...

FROM gcr.io/distroless/static:nonroot
WORKDIR /
COPY --from=builder /workspace/controller-service .
USER 65532:65532
ENTRYPOINT ["/controller-service"]
