FROM golang:1.22 AS builder
ARG TARGETOS
ARG TARGETARCH

WORKDIR /workspace
COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod \ 
    go mod download

COPY gateway/ ./gateway
COPY ptero-wings-controller/ ptero-wings-controller/
COPY internal/ ./internal
COPY api/ api/

RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH}  go build -a -o gateway ./gateway/cmd/main.go

FROM gcr.io/distroless/static:nonroot
WORKDIR /
COPY --from=builder /workspace/gateway .
USER 65532:65532
EXPOSE 8090
ENTRYPOINT ["/gateway"]
