apiVersion: gameserver.pterodactyl.io/v1alpha1
kind: GameServerClass
metadata:
  name: minecraft-vanilla
spec:
  gameType: minecraft
  defaultImage: itzg/minecraft-server:latest
  defaultStartup:
    raw: java -Xmx{{SERVER_MEMORY}}M -jar "{{SERVER_JARFILE}}"
    variables:
      SERVER_MEMORY: "1024"
      SERVER_JARFILE: server.jar
  defaultResources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "2Gi"
  defaultStorage:
    size: 10Gi
    accessMode: ReadWriteOnce
    mountPath: /data
  defaultNetwork:
    serviceType: NodePort
    nodePortAllocation:
      count: 2
      containerStartPort: 25565
  placementDefaults:
    nodeSelector:
      kubernetes.io/os: linux
